spring:
  datasource:
    url: jdbc:mariadb://hackathon.chd0zpcvgayq.ap-northeast-2.rds.amazonaws.com/peter
    # url 형식은 jdbc:mysql://RDS의 EndPoint/내부 DB 스키마명 입니다.
    username: admin
    password: ENC(iPTVN/vBgylpt/IXPDt3kN1Ej40GuaWI)
  jpa:
    hibernate:
      ddl-auto: update